version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: finance-app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/financedb
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
